apiVersion: v1 
kind: ConfigMap
metadata:
  name: usermgmt-dbcreation-script
data:
  mysql_usermgmt.sql: |
    DROP DATABASE IF EXISTS demo;
    CREATE DATABASE demo;

#this config map you can compare the same as user data. 